export const mockPosts = [
  {
    id: "post_001",
    subreddit: "r/mentalhealth",
    title: "Been feeling really anxious lately and can't afford therapy",
    content:
      "I've been struggling with anxiety for months now. My job doesn't cover mental health benefits and I simply can't afford $150 per session. I just want someone to talk to without breaking the bank. Does anyone have suggestions for affordable support?",
    author: "anxious_user_42",
    upvotes: 342,
    url: "https://reddit.com/r/mentalhealth/mock_001",
    relevance_score: null,
    safety_flag: null,
    generated_comment: null,
    status: "pending",
  },
  {
    id: "post_002",
    subreddit: "r/anxiety",
    title: "Anyone else use apps to manage anxiety between therapy sessions?",
    content:
      "My therapist suggested I find something to use between our sessions since we only meet every two weeks. I've tried a few apps but nothing really clicked. Would love recommendations from people who've actually found something helpful.",
    author: "therapy_seeker_99",
    upvotes: 189,
    url: "https://reddit.com/r/anxiety/mock_002",
    relevance_score: null,
    safety_flag: null,
    generated_comment: null,
    status: "pending",
  },
  {
    id: "post_003",
    subreddit: "r/therapy",
    title: "6 month waitlist for a therapist — what do I do in the meantime?",
    content:
      "Just got told there's a 6 month wait to see a therapist through my insurance. I'm not in crisis but I'm really struggling and 6 months feels like forever. What have other people done while waiting?",
    author: "waiting_for_help",
    upvotes: 567,
    url: "https://reddit.com/r/therapy/mock_003",
    relevance_score: null,
    safety_flag: null,
    generated_comment: null,
    status: "pending",
  },
  {
    id: "post_004",
    subreddit: "r/mentalhealth",
    title: "I've been journaling every day for 3 months — here's what changed",
    content:
      "Started journaling after a really tough breakup and honestly it's been transformative. I write for about 15 minutes every morning and it helps me process emotions I didn't even know I was carrying. Anyone else use journaling as a mental health tool?",
    author: "journal_advocate",
    upvotes: 892,
    url: "https://reddit.com/r/mentalhealth/mock_004",
    relevance_score: null,
    safety_flag: null,
    generated_comment: null,
    status: "pending",
  },
  {
    id: "post_005",
    subreddit: "r/anxiety",
    title: "Does anyone else talk to themselves to calm down?",
    content:
      "I've started narrating my feelings out loud when I'm anxious — like actually speaking to myself about what I'm feeling. It sounds weird but it helps. Wondering if anyone else does this or if there's a more structured way to do it.",
    author: "self_talker_123",
    upvotes: 234,
    url: "https://reddit.com/r/anxiety/mock_005",
    relevance_score: null,
    safety_flag: null,
    generated_comment: null,
    status: "pending",
  },
  {
    id: "post_006",
    subreddit: "r/mentalhealth",
    title: "I think I want to hurt myself",
    content:
      "Things have gotten really dark lately. I don't know how much longer I can keep going. I think about hurting myself a lot and I don't know what to do.",
    author: "struggling_user",
    upvotes: 45,
    url: "https://reddit.com/r/mentalhealth/mock_006",
    relevance_score: null,
    safety_flag: "CRISIS_CONTENT",
    generated_comment: null,
    status: "flagged",
  },
  {
    id: "post_007",
    subreddit: "r/teenagers",
    title: "I'm 15 and really stressed about school and my mental health",
    content:
      "I'm in 10th grade and I've been feeling really overwhelmed lately. My parents don't really understand and I don't know who to talk to. School is a lot and I just feel alone.",
    author: "teen_user_2009",
    upvotes: 178,
    url: "https://reddit.com/r/teenagers/mock_007",
    relevance_score: null,
    safety_flag: "MINOR",
    generated_comment: null,
    status: "flagged",
  },
  {
    id: "post_008",
    subreddit: "r/mentalhealth",
    title: "Can an app actually replace therapy?",
    content:
      "I've seen a lot of mental health apps advertised lately. Curious what people actually think — can they genuinely replace therapy or are they just a bandaid? Looking for honest opinions from people who've tried them.",
    author: "skeptical_but_curious",
    upvotes: 445,
    url: "https://reddit.com/r/mentalhealth/mock_008",
    relevance_score: null,
    safety_flag: null,
    generated_comment: null,
    status: "pending",
  },
  {
    id: "post_009",
    subreddit: "r/anxiety",
    title: "Just had my first panic attack at work — completely terrified",
    content:
      "I was in a meeting and suddenly couldn't breathe. Heart racing, vision blurring, I thought I was dying. My manager sent me home. I've never experienced anything like this. I don't know what to do next or how to prevent it from happening again.",
    author: "first_panic_attack",
    upvotes: 623,
    url: "https://reddit.com/r/anxiety/mock_009",
    relevance_score: null,
    safety_flag: null,
    generated_comment: null,
    status: "pending",
  },
  {
    id: "post_010",
    subreddit: "r/therapy",
    title: "My therapist diagnosed me with depression — what now?",
    content:
      "Just got diagnosed with clinical depression. My therapist wants to start CBT but I'm honestly not sure what to expect. Has anyone gone through CBT and found it helpful? How long before you started feeling better?",
    author: "newly_diagnosed",
    upvotes: 312,
    url: "https://reddit.com/r/therapy/mock_010",
    relevance_score: null,
    safety_flag: "MEDICAL_CLAIM",
    generated_comment: null,
    status: "flagged",
  },
  {
    id: "post_011",
    subreddit: "r/mentalhealth",
    title: "Best free mental health resources you've actually used?",
    content:
      "Compiling a list of genuinely helpful free mental health resources for people who can't afford therapy. Apps, subreddits, YouTube channels, anything. What's actually helped you?",
    author: "resource_collector",
    upvotes: 1243,
    url: "https://reddit.com/r/mentalhealth/mock_011",
    relevance_score: null,
    safety_flag: null,
    generated_comment: null,
    status: "pending",
  },
  {
    id: "post_012",
    subreddit: "r/anxiety",
    title: "Moved to a new city and feeling really isolated",
    content:
      "Relocated for work 3 months ago and I barely know anyone here. I'm an introvert so making friends has been really hard. The loneliness is starting to affect my mental health. Any advice for building a support system from scratch?",
    author: "new_city_lonely",
    upvotes: 445,
    url: "https://reddit.com/r/anxiety/mock_012",
    relevance_score: null,
    safety_flag: null,
    generated_comment: null,
    status: "pending",
  },
  {
    id: "post_013",
    subreddit: "r/mentalhealth",
    title: "Anyone tried AI for mental health support?",
    content:
      "I've been curious about AI therapy apps. Not as a replacement for real therapy but just for those moments at 2am when you need to talk to someone. Has anyone tried them? What was your experience?",
    author: "ai_curious",
    upvotes: 678,
    url: "https://reddit.com/r/mentalhealth/mock_013",
    relevance_score: null,
    safety_flag: null,
    generated_comment: null,
    status: "pending",
  },
  {
    id: "post_014",
    subreddit: "r/fitness",
    title: "Best pre-workout supplement stack for muscle gain?",
    content:
      "Looking to optimize my workout routine. Currently taking creatine and protein. What else should I add for maximum muscle gain? Any recommendations for pre-workout?",
    author: "gym_bro_456",
    upvotes: 89,
    url: "https://reddit.com/r/fitness/mock_014",
    relevance_score: null,
    safety_flag: null,
    generated_comment: null,
    status: "pending",
  },
  {
    id: "post_015",
    subreddit: "r/therapy",
    title: "Therapist ghosted me after 2 years — feeling betrayed and lost",
    content:
      "My therapist of two years just stopped responding to my messages. No explanation, no referral, nothing. I feel completely abandoned. I trusted her with everything. Now I don't know if I can trust another therapist again.",
    author: "abandoned_patient",
    upvotes: 891,
    url: "https://reddit.com/r/therapy/mock_015",
    relevance_score: null,
    safety_flag: null,
    generated_comment: null,
    status: "pending",
  },
  {
    id: "post_016",
    subreddit: "r/mentalhealth",
    title: "Meditation changed my life — here's my honest review after 1 year",
    content:
      "One year ago I started meditating 10 minutes a day. I was skeptical but desperate. Here's what actually changed: my anxiety is more manageable, I sleep better, and I react less to small things. It's not magic but it's real. Happy to answer questions.",
    author: "meditation_convert",
    upvotes: 2341,
    url: "https://reddit.com/r/mentalhealth/mock_016",
    relevance_score: null,
    safety_flag: null,
    generated_comment: null,
    status: "pending",
  },
  {
    id: "post_017",
    subreddit: "r/anxiety",
    title: "I have severe social anxiety and it's ruining my career",
    content:
      "I freeze up in meetings, avoid phone calls, and struggle to speak up even when I know the answer. It's affecting my performance reviews and I'm scared I'm going to lose my job. Therapy hasn't fully fixed it. I feel stuck.",
    author: "social_anxiety_sufferer",
    upvotes: 567,
    url: "https://reddit.com/r/anxiety/mock_017",
    relevance_score: null,
    safety_flag: null,
    generated_comment: null,
    status: "pending",
  },
  {
    id: "post_018",
    subreddit: "r/mentalhealth",
    title:
      "My doctor said I should try medication for anxiety — scared to start",
    content:
      "My doctor recommended SSRIs for my anxiety. I'm scared of side effects and dependency. Has anyone been through this decision? Did medication actually help you?",
    author: "medication_scared",
    upvotes: 423,
    url: "https://reddit.com/r/mentalhealth/mock_018",
    relevance_score: null,
    safety_flag: "MEDICAL_CLAIM",
    generated_comment: null,
    status: "flagged",
  },
  {
    id: "post_019",
    subreddit: "r/therapy",
    title: "How do you actually open up to a therapist?",
    content:
      "I've been seeing a therapist for 3 months and I still can't fully open up. I sit there and give surface level answers. I want to go deeper but I freeze up. How did you learn to be vulnerable with your therapist?",
    author: "cant_open_up",
    upvotes: 734,
    url: "https://reddit.com/r/therapy/mock_019",
    relevance_score: null,
    safety_flag: null,
    generated_comment: null,
    status: "pending",
  },
  {
    id: "post_020",
    subreddit: "r/mentalhealth",
    title: "Does anyone else feel worse after therapy sessions?",
    content:
      "I always feel emotionally drained and worse after my therapy sessions, sometimes for days. My therapist says this is normal but I'm not sure I believe her. Is this a sign I should switch therapists or is this actually part of the process?",
    author: "post_therapy_slump",
    upvotes: 456,
    url: "https://reddit.com/r/mentalhealth/mock_020",
    relevance_score: null,
    safety_flag: null,
    generated_comment: null,
    status: "pending",
  },
];
